import { Montserrat } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "@/components/Navbar";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
   icons: {
    icon: "/logo-short.png",   // favicon
    shortcut: "/logo-short.png",
    apple: "/logo-short.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo-short.png" sizes="any" />
      </head>
      <body className={`${montserrat.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
